-- 01_account_setup.sql
-- One-time bootstrap: DB, WH, schemas, roles, grants.
-- Run as ACCOUNTADMIN.
-- Names mirror ami_env_dev.cfg from prod.

USE ROLE ACCOUNTADMIN;

-- Database
CREATE DATABASE IF NOT EXISTS AMI_DEMO_DB
    COMMENT = 'AMI native Git integration demo. Mirrors DEV env.';

-- Warehouse (mirrors prod NONPROD_AMI_ADMIN_WH)
CREATE WAREHOUSE IF NOT EXISTS NONPROD_AMI_ADMIN_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
         AUTO_SUSPEND = 60
         AUTO_RESUME = TRUE
         INITIALLY_SUSPENDED = TRUE
         COMMENT = 'Demo warehouse.';

-- 8 schemas that prod AMI uses
USE DATABASE AMI_DEMO_DB;
CREATE SCHEMA IF NOT EXISTS AMICORP    COMMENT = 'CORP_SCH';
CREATE SCHEMA IF NOT EXISTS AMICOMM    COMMENT = 'COMM_SCH';
CREATE SCHEMA IF NOT EXISTS FRAMEWORK  COMMENT = 'FRMWK_SCH';
CREATE SCHEMA IF NOT EXISTS AMIRPTS    COMMENT = 'RPTS_SCH';
CREATE SCHEMA IF NOT EXISTS AMISTAGE   COMMENT = 'STAGE_SCH';
CREATE SCHEMA IF NOT EXISTS XREF       COMMENT = 'XREF_SCH';
CREATE SCHEMA IF NOT EXISTS AMICIAP    COMMENT = 'CIAP_SCH';
CREATE SCHEMA IF NOT EXISTS AMIINT     COMMENT = 'INT_SCH';

-- We don't use PUBLIC
DROP SCHEMA IF EXISTS AMI_DEMO_DB.PUBLIC;

-- Roles (mirrors ami_env_dev.cfg)
CREATE ROLE IF NOT EXISTS DEV_AMI_ADMIN_ROLE       COMMENT = 'Owner role (= RL_NAME)';
CREATE ROLE IF NOT EXISTS DEV_AMI_LOAD_ROLE        COMMENT = 'Loader (= AMI_MAT_ROLE)';
CREATE ROLE IF NOT EXISTS DEV_AMI_SELECT_ROLE      COMMENT = 'Read only (= AMI_SEL_ROLE)';
CREATE ROLE IF NOT EXISTS DEV_AMI_MLS_ROLE         COMMENT = 'MLS (= AMI_MLS_ROLE)';
CREATE ROLE IF NOT EXISTS DEV_AMI_PBI_ROLE         COMMENT = 'Power BI (= AMI_PBI_ROLE)';
CREATE ROLE IF NOT EXISTS NONPROD_AMI_SUPPORT_ROLE COMMENT = 'Support / ops monitor';

-- Role hierarchy
GRANT ROLE DEV_AMI_ADMIN_ROLE       TO ROLE SYSADMIN;
GRANT ROLE DEV_AMI_LOAD_ROLE        TO ROLE DEV_AMI_ADMIN_ROLE;
GRANT ROLE DEV_AMI_SELECT_ROLE      TO ROLE DEV_AMI_ADMIN_ROLE;
GRANT ROLE DEV_AMI_MLS_ROLE         TO ROLE DEV_AMI_ADMIN_ROLE;
GRANT ROLE DEV_AMI_PBI_ROLE         TO ROLE DEV_AMI_ADMIN_ROLE;
GRANT ROLE NONPROD_AMI_SUPPORT_ROLE TO ROLE SYSADMIN;

-- Give my user the admin + support roles so USE ROLE works without re-login
GRANT ROLE DEV_AMI_ADMIN_ROLE       TO USER RAVITEJA0012;
GRANT ROLE NONPROD_AMI_SUPPORT_ROLE TO USER RAVITEJA0012;

-- Warehouse grants
GRANT USAGE   ON WAREHOUSE NONPROD_AMI_ADMIN_WH TO ROLE DEV_AMI_ADMIN_ROLE;
GRANT USAGE   ON WAREHOUSE NONPROD_AMI_ADMIN_WH TO ROLE DEV_AMI_LOAD_ROLE;
GRANT USAGE   ON WAREHOUSE NONPROD_AMI_ADMIN_WH TO ROLE DEV_AMI_SELECT_ROLE;
GRANT MONITOR ON WAREHOUSE NONPROD_AMI_ADMIN_WH TO ROLE NONPROD_AMI_SUPPORT_ROLE;

-- DB and schemas owned by ADMIN role so deploys create objects under it
GRANT OWNERSHIP ON DATABASE AMI_DEMO_DB                TO ROLE DEV_AMI_ADMIN_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE AMI_DEMO_DB TO ROLE DEV_AMI_ADMIN_ROLE COPY CURRENT GRANTS;

-- Downstream consumer roles
GRANT USAGE ON DATABASE AMI_DEMO_DB TO ROLE DEV_AMI_LOAD_ROLE;
GRANT USAGE ON DATABASE AMI_DEMO_DB TO ROLE DEV_AMI_SELECT_ROLE;
GRANT USAGE ON DATABASE AMI_DEMO_DB TO ROLE DEV_AMI_MLS_ROLE;
GRANT USAGE ON DATABASE AMI_DEMO_DB TO ROLE DEV_AMI_PBI_ROLE;
GRANT USAGE ON DATABASE AMI_DEMO_DB TO ROLE NONPROD_AMI_SUPPORT_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE AMI_DEMO_DB    TO ROLE DEV_AMI_LOAD_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AMI_DEMO_DB    TO ROLE DEV_AMI_SELECT_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AMI_DEMO_DB    TO ROLE NONPROD_AMI_SUPPORT_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AMI_DEMO_DB TO ROLE DEV_AMI_LOAD_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AMI_DEMO_DB TO ROLE DEV_AMI_SELECT_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AMI_DEMO_DB TO ROLE NONPROD_AMI_SUPPORT_ROLE;

-- Verify
SHOW WAREHOUSES LIKE 'NONPROD_AMI_ADMIN_WH';
SHOW DATABASES LIKE 'AMI_DEMO_DB';
SHOW SCHEMAS IN DATABASE AMI_DEMO_DB;

-- SHOW ROLES doesn't take compound LIKE, so we filter via RESULT_SCAN
SHOW ROLES;
SELECT "name", "owner", "comment"
  FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
 WHERE "name" LIKE 'DEV_AMI_%' OR "name" LIKE 'NONPROD_AMI_%'
 ORDER BY "name";
