---------------------------------------------------------------------
-- Script   : 03_keypair_auth.sql
-- Purpose  : Phase 2 bootstrap. Register the GitHub Actions service
--            auth public key on RAVITEJA0012, and grant WRITE on the
--            GIT REPOSITORY so DEV_AMI_ADMIN_ROLE can FETCH from CI.
-- Run as   : ACCOUNTADMIN
-- Run when : Once. Re-run only if you rotate the keypair.
--
-- Notes    : Public key body below was generated by
--            `openssl genrsa 2048 | openssl pkcs8 -topk8 ...` on
--            Windows Git Bash, May 19 2026, at ~/.snowflake-demo-ci/.
--
-- Valid GIT REPOSITORY privileges per Snowflake docs:
--   { READ, WRITE }  -- OPERATE is NOT a valid privilege for this object.
--   Reference: https://docs.snowflake.com/en/sql-reference/sql/grant-privilege
---------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;

-- ===================================================================
-- 1. Register the public key on RAVITEJA0012
--    User keeps password auth AND gets key-pair auth simultaneously.
-- ===================================================================
ALTER USER RAVITEJA0012 SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1Za2MSG+bSCMTh8h61Ty+q1iLALXvtykdvuVleBAPoNSVp5xxnOaJNRn3Oi836JTsLeVEIvdHjlpNz6Ic2H6eR7oE5lDC/p06gL0BnjqTQSdNdsnUfSgrrpgMhmF1PYReDBBOD2SAFlh11K0kbAIDSYfGLDa7bpHZK5OTvzrg7MouaeubMP9XN2/icgQf/GF1tkqnppXVaoE2155sC3o/+DM+JO97T5f7bPTwiByW0wBXbG/P4HffChyE1iL66hY7ZNpXDiQVmmgPhj2GcI03oINTfzD1acJ9m8OK6XkWXnFp4kV+FR8E151DX9iAPEsgmZGDyKT7rLQt+8x8q0sEwIDAQAB';

-- ===================================================================
-- 2. Grant WRITE on the GIT REPOSITORY so DEV_AMI_ADMIN_ROLE can
--    FETCH from the remote (i.e. update the local Snowflake clone)
--    without needing ACCOUNTADMIN. The CI runner uses this role.
-- ===================================================================
GRANT WRITE ON GIT REPOSITORY AMI_DEMO_DB.GIT_OPS.AMI_GIT_REPO
    TO ROLE DEV_AMI_ADMIN_ROLE;

-- ===================================================================
-- 3. Verify the public key fingerprint via DESC USER
--    (SHOW USERS only exposes has_rsa_public_key boolean; the actual
--    fingerprint comes from DESCRIBE USER.)
-- ===================================================================
DESC USER RAVITEJA0012;

SELECT "property", "value"
  FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
 WHERE "property" IN ('RSA_PUBLIC_KEY_FP', 'RSA_PUBLIC_KEY');

-- ===================================================================
-- 4. Verify grants on the GIT REPOSITORY
-- ===================================================================
SHOW GRANTS ON GIT REPOSITORY AMI_DEMO_DB.GIT_OPS.AMI_GIT_REPO;