-- 10_framework_tables.sql - DCM DEFINE versions of EMAIL_BODY_DISPLAY_CONFIG, DEPLOY_LOG, PROCESS_LOG.

DEFINE TABLE {{ env_db }}.{{ frmwk_sch }}.EMAIL_BODY_DISPLAY_CONFIG (
    PROCESS_NAME        VARCHAR(100) NOT NULL,
    EMAIL_BODY_SECTION  VARCHAR(50)  NOT NULL,
    EMAIL_BODY_DISPLAY  VARCHAR(1)   NOT NULL,
    CREATE_BY_ID        VARCHAR(200) NOT NULL DEFAULT CURRENT_ROLE(),
    CREATE_DTTM         TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_BY_ID        VARCHAR(200) NOT NULL DEFAULT CURRENT_ROLE(),
    UPDATE_DTTM         TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_EMAIL_BODY_DISPLAY_CONFIG PRIMARY KEY (PROCESS_NAME, EMAIL_BODY_SECTION)
)
COMMENT = 'Per-process email body section toggles. DCM-managed.';

DEFINE TABLE {{ env_db }}.{{ frmwk_sch }}.DEPLOY_LOG (
    DEPLOY_ID         NUMBER(38,0) IDENTITY(1,1) NOT NULL,
    GIT_COMMIT_HASH   VARCHAR(64),
    GIT_BRANCH        VARCHAR(200),
    DEPLOYED_BY_USER  VARCHAR(200) NOT NULL DEFAULT CURRENT_USER(),
    DEPLOYED_BY_ROLE  VARCHAR(200) NOT NULL DEFAULT CURRENT_ROLE(),
    DEPLOY_STATUS     VARCHAR(20)  NOT NULL DEFAULT 'STARTED',
    STATUS_DESC       VARCHAR(4000),
    DEPLOY_START_TS   TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    DEPLOY_END_TS     TIMESTAMP_TZ,
    CONSTRAINT PK_DEPLOY_LOG PRIMARY KEY (DEPLOY_ID)
)
COMMENT = 'One row per deploy. DCM-managed.';

DEFINE TABLE {{ env_db }}.{{ frmwk_sch }}.PROCESS_LOG (
    LOG_ID         NUMBER(38,0) IDENTITY(1,1) NOT NULL,
    PROCESS_ID     VARCHAR(100),
    PROCESS_NAME   VARCHAR(100),
    FILE_ID        VARCHAR(100),
    COMPONENT      VARCHAR(100),
    PROC_STATUS    VARCHAR(20),
    STATUS_DESC    VARCHAR(4000),
    LOG_TS         TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    LOGGED_BY_ROLE VARCHAR(200) NOT NULL DEFAULT CURRENT_ROLE(),
    CONSTRAINT PK_PROCESS_LOG PRIMARY KEY (LOG_ID)
)
COMMENT = 'Per-step process log. DCM-managed.';

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE {{ env_db }}.{{ frmwk_sch }}.EMAIL_BODY_DISPLAY_CONFIG TO ROLE {{ ami_mat_role }};
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE {{ env_db }}.{{ frmwk_sch }}.DEPLOY_LOG               TO ROLE {{ ami_mat_role }};
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE {{ env_db }}.{{ frmwk_sch }}.PROCESS_LOG              TO ROLE {{ ami_mat_role }};

GRANT SELECT ON TABLE {{ env_db }}.{{ frmwk_sch }}.EMAIL_BODY_DISPLAY_CONFIG TO ROLE {{ ami_sel_role }};
GRANT SELECT ON TABLE {{ env_db }}.{{ frmwk_sch }}.DEPLOY_LOG               TO ROLE {{ ami_sel_role }};
GRANT SELECT ON TABLE {{ env_db }}.{{ frmwk_sch }}.PROCESS_LOG              TO ROLE {{ ami_sel_role }};
