-- 30_fact_meter_reads.sql - DCM DEFINE version of FACT_METER_READS.

DEFINE TABLE {{ env_db }}.{{ stage_sch }}.FACT_METER_READS (
    READ_ID                NUMBER(38,0) NOT NULL,
    METER_KEY              NUMBER(18,0) NOT NULL,
    DEVICE_MFG_NBR         VARCHAR(50),
    SERVICE_POINT_ID       VARCHAR(50),
    READING_TYPE_CODE      VARCHAR(50),
    READING_QUALITY_CODE   VARCHAR(50),
    READING_SOURCE_CODE    VARCHAR(50),
    MEASUREMENT_DATETIME   TIMESTAMP_NTZ,
    MEASUREMENT_QUANTITY   NUMBER(18,6),
    DST_FLAG               VARCHAR(1)    DEFAULT '0',
    FILE_NAME              VARCHAR(500),
    FILE_REC_NUM           NUMBER(38,0),
    PROCESS_ID             VARCHAR(100),
    DATA_ERROR_IND         VARCHAR(1)    DEFAULT 'N',
    DATA_QUALITY_ERROR     VARCHAR(500),
    DATA_QUALITY_MESSAGE   VARCHAR(4000),
    ACTIVE_IND             BOOLEAN       NOT NULL DEFAULT TRUE,
    CREATE_BY_ID           VARCHAR(200)  NOT NULL DEFAULT CURRENT_ROLE(),
    CREATE_DTTM            TIMESTAMP_TZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_BY_ID           VARCHAR(200)  NOT NULL DEFAULT CURRENT_ROLE(),
    UPDATE_DTTM            TIMESTAMP_TZ  NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FACT_METER_READS PRIMARY KEY (READ_ID)
)
COMMENT = 'Validated reads fact. DCM-managed.';

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE {{ env_db }}.{{ stage_sch }}.FACT_METER_READS TO ROLE {{ ami_mat_role }};
GRANT SELECT ON TABLE {{ env_db }}.{{ stage_sch }}.FACT_METER_READS TO ROLE {{ ami_sel_role }};
