--!jinja
-- 10_FrameworkConfig_DDL_v1.0.sql
-- EMAIL_BODY_DISPLAY_CONFIG: per-process toggles for email body sections.
-- Same shape as prod (Validated_Reads_Load_Email_Config_DML).
-- Audit cols default to CURRENT_ROLE() and CURRENT_TIMESTAMP() so INSERTs don't need them.

USE SCHEMA {{ frmwk_sch }};

CREATE OR ALTER TABLE EMAIL_BODY_DISPLAY_CONFIG (
    PROCESS_NAME        VARCHAR(100)  NOT NULL  COMMENT 'Process this row applies to',
    EMAIL_BODY_SECTION  VARCHAR(50)   NOT NULL  COMMENT 'Section key (DATA_PROCESSED, etc.)',
    EMAIL_BODY_DISPLAY  VARCHAR(1)    NOT NULL  COMMENT 'Y or N',
    CREATE_BY_ID        VARCHAR(200)  NOT NULL  DEFAULT CURRENT_ROLE(),
    CREATE_DTTM         TIMESTAMP_TZ  NOT NULL  DEFAULT CURRENT_TIMESTAMP(),
    UPDATE_BY_ID        VARCHAR(200)  NOT NULL  DEFAULT CURRENT_ROLE(),
    UPDATE_DTTM         TIMESTAMP_TZ  NOT NULL  DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_EMAIL_BODY_DISPLAY_CONFIG PRIMARY KEY (PROCESS_NAME, EMAIL_BODY_SECTION)
)
COMMENT = 'Per-process email body section toggles. Demo mirror of prod.';

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLE EMAIL_BODY_DISPLAY_CONFIG TO ROLE {{ ami_mat_role }};
GRANT SELECT ON TABLE EMAIL_BODY_DISPLAY_CONFIG TO ROLE {{ ami_sel_role }};
GRANT SELECT ON TABLE EMAIL_BODY_DISPLAY_CONFIG TO ROLE {{ ami_support_role }};
